apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploying-spring-server
  labels:
    app: app-spring-server
  namespace: prometheus
spec:
  replicas: 3  # the number of instances you want to run
  selector:
    matchLabels:
      app: app-spring-server
  template:
    metadata:
      labels:
        app: app-spring-server
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/demo-0.0.1-SNAPSHOT/metrics'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: container-spring-boot
          image: samyak1326/tomcat-spring

          # replace with your Docker Hub image

          ports:
            - containerPort: 8080  # the port your container exposes
